### ISSUE TITLE
Read demo path from args

### ISSUE THREAD

**Issue by rulojuka** [mateusab/highlights-machine#3]
Something like this should work: `go run main.go mydemos/insane-1k-taco-vs-liquid-mlg`

Hint: You are already reading the args: https://github.com/mateusab/highlights-machine/blob/master/main.go#L29

**Comment by mateusab** [comment]
https://github.com/mateusab/highlights-machine/commit/6f8155c13d2b4adc996fed0cdd2a9b413371c6ac

solved
